### ISSUE TITLE
monaparty/counterparty-server:latest failed 

### ISSUE THREAD

**Issue by kmn** [monaparty/federatednode#1]
`monaparty/counterparty-server:latest` fails after the process starts.

`docker logs `  outputs logs as below.
How do I fix this?

```
python3: can't open file 'setup.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'counterparty-cli' distribution was not found and is required by the application
```

**Comment by cryptcoin-junkey** [comment]
Please have a look https://qiita.com/cryptcoin-junkey/items/fc37aab4fc7347c2ee4a if you've not read yet.
Referring to  the comment there, at least he/she succeeded to run the federated node.

**Comment by cryptcoin-junkey** [comment]
I close this issue. Please reopen if required.
